front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /core